INSERT INTO ITEM_TYPE (TYPE, CREATED_AT, UPDATED_AT)
VALUES ('지출', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ITEM_TYPE (TYPE, CREATED_AT, UPDATED_AT)
VALUES ('수입', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());